### ISSUE TITLE
(Tier 1) As a developer, I want to be able to:

### ISSUE THREAD

**Issue by radical-ube** [2004-wdf-capstone-d/capstone-spotify#16]
- [x] store login credentials in MongoDB #18 
- [x] connect to the Spotify API to display popular artists and user information #20 
- [x] utilize placeholder JSON data for d3 display #21
