### ISSUE TITLE
(Tier 1) As a visitor, I want to be able to:

### ISSUE THREAD

**Issue by radical-ube** [2004-wdf-capstone-d/capstone-spotify#7]
- [x] see a (pre-determined) data visual upon entering the site #9 
- [x] view a list of popular artists #11 
- [x] log in with my spotify account (OAuth2) #12
